# Generated by Django 5.1.3 on 2024-11-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Product'), (2, 'Service')])),
                ('item_status', models.PositiveSmallIntegerField(choices=[(1, 'Available'), (2, 'Out of Stock'), (3, 'Discontinued')], default=1)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
